@URLCompare
Feature: Validate redirect

@javascript
Scenario Outline: redirect validation
Given I maximise the window
Then I Compare RedirectUrl "<FirstURL>" and "<SecondURL>"

Examples:
|FirstURL  |SecondURL   |
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/7202.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E6%82%A8%E6%8B%A5%E6%9C%89%E6%88%91%E4%BB%AC%E9%9C%80%E8%A6%81%E7%9A%84%E7%89%B9%E8%B4%A8%E5%90%97%EF%BC%9F	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/7202.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E6%82%A8%E6%8B%A5%E6%9C%89%E6%88%91%E4%BB%AC%E9%9C%80%E8%A6%81%E7%9A%84%E7%89%B9%E8%B4%A8%E5%90%97%EF%BC%9F	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/7203.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E5%8A%A0%E5%85%A5%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/7204.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E6%8B%9B%E8%81%98%E9%A1%BE%E9%97%AE%E7%9A%84%E8%A7%92%E8%89%B2%E5%AE%9A%E4%BD%8D	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/7204.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E6%8B%9B%E8%81%98%E9%A1%BE%E9%97%AE%E7%9A%84%E8%A7%92%E8%89%B2%E5%AE%9A%E4%BD%8D	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/7205.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E5%91%98%E5%B7%A5%E7%A6%8F%E5%88%A9	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/7206.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97%E5%9B%BD%E9%99%85%E8%81%8C%E4%B8%9A%E5%8F%91%E5%B1%95	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/7206.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97%E5%9B%BD%E9%99%85%E8%81%8C%E4%B8%9A%E5%8F%91%E5%B1%95	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/7206.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97%E5%9B%BD%E9%99%85%E8%81%8C%E4%B8%9A%E5%8F%91%E5%B1%95	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/7269.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E5%8A%A0%E5%85%A5%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8335.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E5%8A%A0%E5%85%A5%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8335.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E5%8A%A0%E5%85%A5%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8344.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E6%82%A8%E6%8B%A5%E6%9C%89%E6%88%91%E4%BB%AC%E9%9C%80%E8%A6%81%E7%9A%84%E7%89%B9%E8%B4%A8%E5%90%97%EF%BC%9F	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8344.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E6%82%A8%E6%8B%A5%E6%9C%89%E6%88%91%E4%BB%AC%E9%9C%80%E8%A6%81%E7%9A%84%E7%89%B9%E8%B4%A8%E5%90%97%EF%BC%9F	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8368.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E5%8A%A0%E5%85%A5%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8368.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E5%8A%A0%E5%85%A5%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8626.html?mc_id=114645	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E5%8A%A0%E5%85%A5%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8626.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E5%8A%A0%E5%85%A5%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8626.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E5%8A%A0%E5%85%A5%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8627.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E5%8A%A0%E5%85%A5%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8627.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E5%8A%A0%E5%85%A5%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8628.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E5%8A%A0%E5%85%A5%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8628.html	|	http://wwwuat.michaelpage.com.cn/%E5%85%B3%E4%BA%8E%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97/%E5%8A%A0%E5%85%A5%E7%B1%B3%E9%AB%98%E8%92%B2%E5%BF%97	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8368.html	|	https://wwwuat.michaelpage.com.cn/work-for-us/apply-now	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8335.html	|	http://wwwuat.michaelpage.com.cn/work-for-us	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8335.html	|	http://wwwuat.michaelpage.com.cn/work-for-us	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8335.html	|	http://wwwuat.michaelpage.com.cn/work-for-us	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8336.html	|	http://wwwuat.michaelpage.com.cn/work-for-us/role-consultant	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8336.html	|	http://wwwuat.michaelpage.com.cn/work-for-us/role-consultant	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8337.html	|	http://wwwuat.michaelpage.com.cn/work-for-us/training-and-development	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8337.html	|	http://wwwuat.michaelpage.com.cn/work-for-us/training-and-development	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8338.html	|	http://wwwuat.michaelpage.com.cn/work-for-us/do-you-have-what-it-takes	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8338.html	|	http://wwwuat.michaelpage.com.cn/work-for-us/do-you-have-what-it-takes	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8339.html	|	http://wwwuat.michaelpage.com.cn/work-for-us/employee-benefits	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8339.html	|	http://wwwuat.michaelpage.com.cn/work-for-us/employee-benefits	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8341.html	|	http://wwwuat.michaelpage.com.cn/work-for-us/why-michael-page-different	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8341.html	|	http://wwwuat.michaelpage.com.cn/work-for-us/why-michael-page-different	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8342.html	|	http://wwwuat.michaelpage.com.cn/work-for-us/core-values	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8342.html	|	http://wwwuat.michaelpage.com.cn/work-for-us/core-values	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8343.html	|	http://wwwuat.michaelpage.com.cn/work-for-us/established-consultant-faqs	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8343.html	|	http://wwwuat.michaelpage.com.cn/work-for-us/established-consultant-faqs	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8344.html	|	http://wwwuat.michaelpage.com.cn/work-for-us/do-you-have-what-it-takes	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8344.html	|	http://wwwuat.michaelpage.com.cn/work-for-us/do-you-have-what-it-takes	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8345.html	|	http://wwwuat.michaelpage.com.cn/work-for-us	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8345.html	|	http://wwwuat.michaelpage.com.cn/work-for-us	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8368.html	|	http://wwwuat.michaelpage.com.cn/work-for-us	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8368.html	|	http://wwwuat.michaelpage.com.cn/work-for-us	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8626.html	|	http://wwwuat.michaelpage.com.cn/work-for-us	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8626.html?mc_id=114644	|	http://wwwuat.michaelpage.com.cn/work-for-us	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8626.html	|	http://wwwuat.michaelpage.com.cn/work-for-us	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8626.html	|	http://wwwuat.michaelpage.com.cn/work-for-us	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8627.html	|	http://wwwuat.michaelpage.com.cn/work-for-us	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8627.html	|	http://wwwuat.michaelpage.com.cn/work-for-us	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8628.html	|	http://wwwuat.michaelpage.com.cn/work-for-us	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8628.html	|	http://wwwuat.michaelpage.com.cn/work-for-us	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8368.html	|	https://wwwuat.michaelpage.com.cn/work-for-us/apply-now	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/11974_CB_pages.v21.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/13733_APAC_brochure.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/pdf/CV_Template-Asiapac.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/11770_s%20china_0728.htm	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/13048.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/19Mar_Share-Services_Invite.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/5Mar2012-Value-chain-transformation.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/6447_hk_exec_broch.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/9Mar2012-Mobile-E-commerce-Invite.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/China_2013_SEF_Final_v2.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/China_H1_2013_Employment_Index.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/China_Market_Entry_Expansion_26Feb.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/ChinaEmployeeIntentionsReport201213v2.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/Cocktails&Networking.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/CPD-Enterprise-Risk-Management-Seminar_1&4.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/HR-Seminar_how-to-work-the-room.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/MichaelPage_201314_China_Employee_Intentions_Reportv2.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/pres0526.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/Presentation%20file_Oct%202010.ppt.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/Slideshow_1.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/Slideshow_2.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/zh/ContentArticle/page/8429.html	|	http://wwwuat.michaelpage.com.cn/	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8226.html	|	http://wwwuat.michaelpage.com.cn/	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8355.html	|	http://wwwuat.michaelpage.com.cn/	|
|	http://wwwuat.michaelpage.com.cn/minisite/Herbalife/Contact.html	|	http://wwwuat.michaelpage.com.cn/	|
|	http://wwwuat.michaelpage.com.cn/minisite/Kohler_CN/apps.html	|	http://wwwuat.michaelpage.com.cn/	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/13018-BR_CN_2012_Global_FS_ZH.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/13470_China-Employee-Intentions-Report-ZH.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/AU_1112_SEF.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/China_2013_SEF_Final.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/ChinaSalaryandEmploymentForecastReport2013_Finance.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/ChinaSalaryandEmploymentForecastReport2013_Legal.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/ChinaSalaryandEmploymentForecastReport2013_Retail.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/CN_EI_Q2-ZH.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/CN_SEF_2012_ZH.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/pdf/e&sc_web.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/pdf/finance_web.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/pdf/p&c_web.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/pdf/r&s_web.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/Websitepdf/11738_CN_EmpIndex_(Chinese)_lr.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/12580_CN_S&EF_2012_FINAL.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/13385-BR_TW_Global-CFO-Report-in-Traditional-Chinese.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/Websitepdf/China_Q1_2012.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/Websitepdf/China-Michael-Page-Employment-Index-Q1-2011.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/ChinaSalaryandEmploymentForecastReport2013_Human_Resource.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/ChinaSalaryandEmploymentForecastReport2013_Procurement&SupplyChain.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/CN_EI_Q2.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/7221.html	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/7251.html	|	http://wwwuat.michaelpage.com.cn/terms-and-conditions	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/7256.html	|	http://wwwuat.michaelpage.com.cn/career-centre	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/7414.html	|	http://wwwuat.michaelpage.com.cn/	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/7417.html	|	http://wwwuat.michaelpage.com.cn/	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/7435.html	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8002.html	|	http://wwwuat.michaelpage.com.cn/career-centre	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/8153.html	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/minisite/Advertising/SouthernCN/premium.html	|	http://reachtalent.michaelpage.com.cn/	|
|	http://wwwuat.michaelpage.com.cn/minisite/coca-cola/contact.html	|	http://wwwuat.michaelpage.com.cn/	|
|	http://wwwuat.michaelpage.com.cn/minisite/Hilton_CN/contact.html	|	http://wwwuat.michaelpage.com.cn/	|
|	http://wwwuat.michaelpage.com.cn/minisite/Imerys/index.html	|	http://wwwuat.michaelpage.com.cn/	|
|	http://wwwuat.michaelpage.com.cn/minisite/Ingram_Micro/contact.html	|	http://wwwuat.michaelpage.com.cn/	|
|	http://wwwuat.michaelpage.com.cn/minisite/Kailong_Rei/index.html	|	http://wwwuat.michaelpage.com.cn/	|
|	http://wwwuat.michaelpage.com.cn/minisite/Kohler_CN/china.html	|	http://wwwuat.michaelpage.com.cn/	|
|	http://wwwuat.michaelpage.com.cn/minisite/Polycom/opps.html	|	http://wwwuat.michaelpage.com.cn/	|
|	http://wwwuat.michaelpage.com.cn/pdf/1626_hk_ci_ss_v7lowres.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/pdf/AU_2007_Finance_SalarySurvey.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/pdf/AU_2007_SC_SalarySurvey.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/10246_cn_EM_S%26EF.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/10246_cn_EM_S&EF.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/10286_CN_Finance_S&EF.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/10287_CN_Fin_serv_S&EF.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/10289_CN_legal_S&EF_v2.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/10290_cn_psc.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/10291_cn_pc_v2.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/10292_CN_R&S_S&EF.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/10293_CN_S%26M_S%26EF.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/10293_CN_S&M_S&EF.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/11078_HK_Marathon_Poster.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/11312_PRC_Pack.v5.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/11957_Final.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/13114-IV_CN_Invite_web-lingnan.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/13160-IC_Operation_Smile_poster_for_MP_website.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/13507_MP_S&EF_HR_print.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/ChinaSalaryandEmploymentForecastReport2013_Financial_Service.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/ChinaSalaryandEmploymentForecastReport2013_Marketing.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/ChinaSalaryandEmploymentForecastReport2013_PropertyConstruction.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/ChinaSalaryandEmploymentForecastReport2013_Sales.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/ChinaSalaryandEmploymentForecastReport2013_Technology.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/CN-EI-FINAL-(small).pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/CPP_March12.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/Websitepdf/Employee-Intentions-Report-China.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/EngineeringSCWebSEF.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/ExeclunchSZ.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/FinanceWebSEF.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/MichaelPageChinaEngineering&SupplyChainSalary&EmploymentForecast2012-zh.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/MichaelPageChinaFinanceSalary&EmploymentForecast2012.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/MichaelPageChinaFinancialServicesSalary%26EmploymentForecast2012.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/MichaelPageChinaFinancialServicesSalary&EmploymentForecast2012.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/MichaelPageChinaHumanResourcesSalary&EmploymentForecast2012.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/MichaelPageChinaHumanResourcesSalary&EmploymentForecast2012-zh.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/MichaelPageChinaLegalSalary&EmploymentForecast2012.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/MichaelPageChinaLegalSalary&EmploymentForecast2012-zh.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/MichaelPageChinaMarketingSalary&EmploymentForecast2012-zh.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/MichaelPageChinaMarketOverviewSalary&EmploymentForecast2012-zh.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/MichaelPageChinaRetail&SourcingSalary&EmploymentForecast2012-zh.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/MichaelPageChinaSalesSalary&EmploymentForecast2012-zh.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/MichaelPageEmploymentIndex_March2010.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/MichaelPageEmploymentIndex_May2010.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/Presentation file_Oct 2010.ppt.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/PropertyConstructionWebSEF.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/RetailSourcingWeb.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/SalesMarketngWebSEF.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/websitepdf/szinvitation.pdf	|	http://wwwuat.michaelpage.com.cn/news-research	|
|	http://wwwuat.michaelpage.com.cn/zh/ContentArticle/page/7207.html	|	http://wwwuat.michaelpage.com.cn/	|
|	http://wwwuat.michaelpage.com.cn/zh/ContentArticle/page/8229.html	|	http://wwwuat.michaelpage.com.cn/	|
|	http://wwwuat.michaelpage.com.cn/ContentArticle/page/7274.html	|	http://wwwuat.michaelpage.com.cn/ 	|
